name: Python Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi

      - name: Rodar testes com unittest
        run: |
          python -m unittest discover -s api/tests

      - name: Rodar testes de integração
        run: pytest tests/
