name: Python Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi

      - name: Rodar testes unitários (unittest)
        run: PYTHONPATH=. python -m unittest discover -s api/tests

      - name: Preparar arquivos de modelo para integração
        run: |
          mkdir -p models
          cp api/models/mlp_model_iris.pkl models/model
          cp api/models/scaler_model.pkl models/scaler_model

      - name: Rodar testes de integração (pytest)
        run: PYTHONPATH=. pytest api/tests/test_integration.py
